package types

type Place struct {
	Name     string `json:"name"`
	Address  string `json:"address"`
	Phone    string `json:"phone"`
	Location struct {
		Lon string `json:"lon"`
		Lat string `json:"lat"`
	}
}
type AutoGenerated struct {
	Hits struct {
		Total struct {
			Value    int    `json:"value"`
			Relation string `json:"relation"`
		} `json:"total"`
		MaxScore float64 `json:"max_score"`
		Hits     []struct {
			Index  string  `json:"_index"`
			Type   string  `json:"_type"`
			ID     string  `json:"_id"`
			Score  float64 `json:"_score"`
			Source struct {
				Name     string `json:"name"`
				Address  string `json:"address"`
				Phone    string `json:"phone"`
				Location struct {
					Lon string `json:"lon"`
					Lat string `json:"lat"`
				} `json:"Location"`
			} `json:"_source"`
		} `json:"hits"`
	} `json:"hits"`
}

const Head = "<!doctype html>\n<html>\n<head>\n   " +
	" <meta charset=\"utf-8\">\n    " +
	"<title>Places</title>\n    " +
	"<meta name=\"description\" content=\"\">\n    " +
	"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n" +
	"</head>\n\n" +
	"<body>\n" +
	"<h5>Total: 13649</h5>\n" +
	"<ul>\n"

type ApiStruct struct {
	Name     string  `json:"name"`
	Total    int     `json:"total"`
	Places   []Place `json:"places"`
	PrevPage int     `json:"prev_page"`
	NextPage int     `json:"next_page"`
	LastPage int     `json:"last_page"`
}

type ApiNear struct {
	Name   string  `json:"name"`
	Places []Place `json:"places"`
}
type TokenJWT struct {
	Token string `json:"token"`
}
