openapi: 3.0.1
info:
  title: Candy Server
  version: 1.0.0
servers:
  - url: /
paths:
  /buy_candy:
    post:
      operationId: buyCandy
      requestBody:
        description: summary of the candy order
        content:
          application/json:
            schema:
              required:
                - candyCount
                - candyType
                - money
              type: object
              properties:
                money:
                  type: integer
                  description: amount of money put into vending machine
                candyType:
                  type: string
                  description: kind of candy
                candyCount:
                  type: integer
                  description: number of candy
        required: false
      responses:
        "201":
          description: purchase succesful
          content:
            application/json:
              schema:
                type: object
                properties:
                  thanks:
                    type: string
                  change:
                    type: integer
        "400":
          description: some error in input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "402":
          description: not enough money
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      x-codegen-request-body-name: order
components: {}
x-original-swagger-version: "2.0"
